# Generated by Django 3.1.3 on 2020-12-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('recipe_image', models.ImageField(upload_to='images')),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
