# Generated by Django 3.1.3 on 2020-12-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.CharField(max_length=500),
        ),
    ]
